development:
  adapter: redis

test:
  adapter: redis

production:
  adapter: redis
  url: redis://redistogo:acca05f3cce8b4932b94fbd091744a4e@tarpon.redistogo.com:10054/
  channel_prefix: tripper_production
